version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: citrus-api
    environment:
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env  

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: citrus-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: citrus-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db